# @Author: xiaocao
# @Date:   2023-04-18 22:08:30
# @Last Modified by:   xiaocao
# @Last Modified time: 2023-04-18 22:22:31

name: ci

on:
  push:
    # branches: ['master', 'develop']
    # 这里注释掉，这里是或的关系
    tags: ["v*"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: wdjoys/guahao
          tags: v1, latest
          registry: docker.io
          dockerfile: dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}